### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by mrengineer** [xadrianzetx/coral-deeplab#12]
Hello,
I am using https://github.com/srihari-humbarwadi/DeepLabV3_Plus-Tensorflow2.0 trained with my dataset. I am going to migrate from GPU to TPU. Thank you for your project!
However I have problem to install it. Please, help to solve problem described hereunder.

Hardware: asus tinker edge t
OS: Tinker_Edge_T-Mendel-Eagle-V3.0.2-20201015
Python: Python 3.7.3

Issue:
I run 
pip3 install git+https://github.com/xadrianzetx/coral-deeplab.git

Collecting git+https://github.com/xadrianzetx/coral-deeplab.git
  Cloning https://github.com/xadrianzetx/coral-deeplab.git to /tmp/pip-req-build-12yqg40c
Collecting numpy>=1.19.5 (from coral-deeplab==0.2)
  Downloading https://files.pythonhosted.org/packages/66/03/818876390c7ff4484d5a05398a618cfdaf0a2b9abb3a7c7ccd59fe181008/numpy-1.21.0.zip (10.3MB)
    100% |████████████████████████████████| 10.3MB 40kB/s 
  Installing build dependencies ... done
**_Collecting tensorflow-gpu==2.4.0 (from coral-deeplab==0.2)
  Could not find a version that satisfies the requirement tensorflow-gpu==2.4.0 (from coral-deeplab==0.2) (from versions: )
No matching distribution found for tensorflow-gpu==2.4.0 (from coral-deeplab==0.2)_**

**Comment by xadrianzetx** [comment]
Hi,

There are no ARM wheels for `tensorflow-gpu` on pypi, but you don't need them if you are just trying to pull precompiled model straight to device.

Install with:

```
pip install git+https://github.com/xadrianzetx/coral-deeplab.git --no-deps
``` 

and pull model to `tflite.Interpreter` like so:

```python
import coral_deeplab as cdl
import tflite_runtime.interpreter as tflite

interpreter = tflite.Interpreter(
    cdl.from_precompiled(cdl.pretrained.EdgeTPUModel.DEEPLAB_V3_DM1),
    experimental_delegates=[tflite.load_delegate('libedgetpu.so.1)]
)
```

**Comment by mrengineer** [comment]
Thank you very much!
Could you please add run-out-of-box examples of inference and training scripts for newbies like me?

**Comment by xadrianzetx** [comment]
[Here](https://coral.ai/docs/edgetpu/tflite-python/#update-existing-tf-lite-code-for-the-edge-tpu) are some good examples of running Edge TPU models, and [here](https://www.tensorflow.org/tutorials/images/transfer_learning) you can find out how to finetune `tf.keras` model. I might add some example scripts later on if there's time.

**Comment by mrengineer** [comment]
Thank you Seems easy Unexpectedly easy
